fix: Undefined task variable in refactoring phase
Fixed NameError where 'task' was referenced but not defined in
_handle_comprehensive_refactoring method.

Changed to get current_task from state:
task.task_id -> current_task.task_id where current_task = state.current_task

This was causing the refactoring phase to crash with:
NameError: name 'task' is not defined